parameters:
    repository.namespaces: []
    repository.instances: []

    tokenDefinitions: []

services:

    queryBuilder:
        class: Silktide\Reposition\QueryBuilder\QueryBuilder
        arguments:
            - @tokenFactory

    tokenFactory:
      class: Silktide\Reposition\QueryBuilder\QueryToken\TokenFactory

    repositoryManager:
        class: Silktide\Reposition\Repository\RepositoryManager
        arguments:
            - @defaultStorage
            - @queryBuilder
            - @defaultMetadataFactory
            - %repository.namespaces%
            - %repository.instances%

    tokenParser:
        class: Silktide\Reposition\QueryBuilder\TokenParser
        arguments:
            - %tokenDefinitions%

    collectionFactory:
      class: Silktide\Reposition\Collection\CollectionFactory
