parameters:
    repository.namespaces: []
    repository.instances: []

    tokenDefinitions: []

services:

    queryBuilder:
        class: Lexide\Reposition\QueryBuilder\QueryBuilder
        arguments:
            - "@tokenFactory"

    tokenFactory:
      class: Lexide\Reposition\QueryBuilder\QueryToken\TokenFactory

    repositoryManager:
        class: Lexide\Reposition\Repository\RepositoryManager
        arguments:
            - "@defaultStorage"
            - "@queryBuilder"
            - "@defaultMetadataFactory"
            - "@defaultEntityFactory"
            - "%repository.namespaces%"
            - "%repository.instances%"

    tokenParser:
        class: Lexide\Reposition\QueryBuilder\TokenParser
        arguments:
            - "%tokenDefinitions%"

    collectionFactory:
        class: Lexide\Reposition\Collection\CollectionFactory

    lexide_reposition.metadataProvider:
        aliasOf: "@repositoryManager"

#### stub services to be aliased by modules

    defaultEntityFactory:
        class: Lexide\Reposition\Hydrator\EntityFactoryInterface

    defaultHydrator:
        class: Lexide\Reposition\Hydrator\HydratorInterface

    defaultMetadataFactory:
        class: Lexide\Reposition\Metadata\EntityMetadataFactoryInterface

    defaultNormaliser:
        class: Lexide\Reposition\Normaliser\NormaliserInterface

    defaultStorage:
        class: Lexide\Reposition\Storage\StorageInterface
